# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julien Appéré - Frontend dev
email: julien.appere@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Frontend dev Mais pas que.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://julienappere.com" # the base hostname & protocol for your site
timezone: Europe/Paris
encoding: utf-8
keep_files: [css,js]
exclude: [README.md]
navigation:
  - title: home
    url: /
  - title: portfolio
    url: /projets/
  - title: cv
    url: /cv
  - title: a propos
    url: /about

social:
  - url: https://github.com/Empreintes
    name: Github
  - url: https://www.linkedin.com/in/julienappere
    name: LinkedIn
  - url: https://twitter.com/Empreintes
    name: Twitter
  - url: http://stackoverflow.com/users/467836/julien
    name: Stackoverflow

# Build settings
markdown: kramdown

#urls
